spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://188.166.255.182:8888/notification-db
    username: notification-db
    password: 8082
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://keycloak.jelay.site/realms/stack-notes
  mail:
    host: smtp.gmail.com
    port: 587
    username: bugzapper.hrd@gmail.com
    password: dbblamycivtocqki
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq.jelay.site
    port: 5672
    virtual-host: /
    ssl:
      enabled: false
keycloak:
  realm: stack-notes
  resource: stack-notes-client
  auth-server-url: https://keycloak.jelay.site/
  credentials:
    secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
    client-id: stack-notes-client
    provider: secret
# Swagger configuration
springdoc:
#  api-docs:
#    path: /notification-service/v3/api-docs
  swagger-ui:
#    path: /notification-service/swagger-ui.html
    oauth:
      client-id: stack-notes-client
      client-secret: tDbzKXKsHvvmFQAJ1bUSR87Dbia2ssfZ
      realm: stack-notes
    tags-sorter: alpha
eureka:
  client:
    service-url:
      defaultZone: https://eureka.jelay.site/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
server:
  port: 8082
